# This will run on Travis' 'new' container-based infrastructure
language: c
sudo: true

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: Matrix-BigInt-library
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/Goalt/Matrix-BigInt-library.git

# Install dependencies
addons:
  apt:
    packages:
      - gcc-avr
      - binutils-avr
      - avr-libc
      - graphviz

before_install:
  - sudo add-apt-repository ppa:vidavidorra/precise-backport -y
  - sudo apt-get update -q
  - sudo apt-get install doxygen -y

# Build your code e.g. by calling make
script:

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
